FROM golang:1.15.11-stretch AS builder

WORKDIR /app
COPY go.mod go.sum .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o main

FROM scratch

COPY --from=builder /app/main .

ENTRYPOINT ["./main"]
