name: Docker Cache Demo

on:
  workflow_dispatch: {}

jobs:
  cache-demo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker build
      run: |
        docker buildx create --use
        docker buildx build -t temp -f docker-buildx/Dockerfile docker-buildx --cache-to=type=local,dest=cache

    - name: ls cache
      run: |
        ls cache
