name: Go Docker Inline Cache Demo

# A trivial example that demonstrates using the buildx --cache-from argument and
# an image on a remote registry to use as the cache.

on:
  workflow_dispatch: {}

jobs:
  cache-demo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Set Docker repo
      id: set-repo
      run: |
        tag=${GITHUB_REF##*/}
        if [[ "$tag" == "master" ]]; then
          tag="latest"
        fi
        echo "::set-output name=repo::surjection/demo-for-cache-from:$tag"

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: go-with-buildx
        file: go-with-buildx/Dockerfile
        push: true
        tags: ${{ steps.set-repo.outputs.repo }}
        cache-from: type=registry,ref=surjection/demo-for-cache-from:latest
        cache-to: type=inline
