name: Use Custom Action

on:
  workflow_dispatch: {}

jobs:
  use-container:
    name: Use custom action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use my-action custom action
        uses: ./my-action
        id: hello
        with:
          who-to-greet: 'bob'
      - name: Display timestamp
        run: |
          echo "The time was ${{ steps.hello.outputs.time }}"
