name: Use Spawn Actions

on:
  workflow_dispatch: {}

jobs:
  exercise-actions:
    name: Exercise Spawn GH Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls
      - name: create data image
        id: create-image
        uses: red-gate/spawn-ci-plugins/github/data-image/create@bump-spawnctl-version
        with:
          dataImageYaml: spawn/image.yaml
      - name: create empty pg container
        id: create-container
        uses: red-gate/spawn-ci-plugins/github/data-container/create@bump-spawnctl-version
        with:
          dataImage: ${{ steps.create-image.outputs.dataImageName }}
          lifetime: '5h'
      - name: save container
        uses: red-gate/spawn-ci-plugins/github/data-container/save@bump-spawnctl-version
        with:
          dataContainer: ${{ steps.create-container.outputs.dataContainerName }}
      - name: reset container
        uses: red-gate/spawn-ci-plugins/github/data-container/reset@bump-spawnctl-version
        with:
          dataContainer: ${{ steps.create-container.outputs.dataContainerName }}
      - name: delete container
        uses: red-gate/spawn-ci-plugins/github/data-container/delete@bump-spawnctl-version
        with:
          dataContainer: ${{ steps.create-container.outputs.dataContainerName }}
env:
  SPAWNCTL_ACCESS_TOKEN: ${{ secrets.SPAWNCTL_ACCESS_TOKEN }}
