name: Use Spawn Actions

on: push

jobs:
  create-container:
    name: Create container
    runs-on: ubuntu-latest
    steps:
      - name: create empty pg container
        uses: red-gate/spawn-ci-plugins/github/data-container/create@run-as-root
        with:
          dataImage: 11780 # An empty postgres image
env:
  SPAWNCTL_ACCESS_TOKEN: ${{ secrets.SPAWNCTL_ACCESS_TOKEN }}

