name: Use Spawn Actions

on: push

jobs:
  use-container:
    name: Use container
    runs-on: ubuntu-latest
    steps:
      - name: create empty pg container
        id: create
        uses: red-gate/spawn-ci-plugins/github/data-container/create@add-lifetime-to-container-create
        with:
          dataImage: 11780 # An empty postgres image
          lifetime: '2h'
      - name: save container
        uses: red-gate/spawn-ci-plugins/github/data-container/save@add-lifetime-to-container-create
        with:
          dataContainer: ${{ steps.create.outputs.dataContainerName }}
      - name: reset container
        uses: red-gate/spawn-ci-plugins/github/data-container/reset@add-lifetime-to-container-create
        with:
          dataContainer: ${{ steps.create.outputs.dataContainerName }}
      - name: delete container
        uses: red-gate/spawn-ci-plugins/github/data-container/delete@add-lifetime-to-container-create
        with:
          dataContainer: ${{ steps.create.outputs.dataContainerName }}
env:
  SPAWNCTL_ACCESS_TOKEN: ${{ secrets.SPAWNCTL_ACCESS_TOKEN }}
