name: Use Spawn Actions

on:
  workflow_dispatch: {}

jobs:
  use-container:
    name: Use container
    runs-on: ubuntu-latest
    steps:
      - name: create empty pg container
        id: create
        uses: red-gate/spawn-ci-plugins/github/data-container/create@main
        with:
          dataImage: 11780 # An empty postgres image
          lifetime: '5h'
      - name: save container
        uses: red-gate/spawn-ci-plugins/github/data-container/save@main
        with:
          dataContainer: ${{ steps.create.outputs.dataContainerName }}
      - name: reset container
        uses: red-gate/spawn-ci-plugins/github/data-container/reset@main
        with:
          dataContainer: ${{ steps.create.outputs.dataContainerName }}
      - name: delete container
        uses: red-gate/spawn-ci-plugins/github/data-container/delete@main
        with:
          dataContainer: ${{ steps.create.outputs.dataContainerName }}
env:
  SPAWNCTL_ACCESS_TOKEN: ${{ secrets.SPAWNCTL_ACCESS_TOKEN }}
